export const EXERCISE_REQUEST = "EXERCISE_REQUEST";

export const EXERCISE_SUCCESSFULL = "EXERCISE_SUCCESSFULL";

export const EXERCISE_FAILURE = "EXERCISE_FAILURE";

export const POST_EXERCISE_SUCCESSFULL = "POST_EXERCISE_SUCCESSFULL";
