export const FOOD_REQUEST = "FOOD_REQUEST";

export const FOOD_SUCCESSFULL = "FOOD_SUCCESSFULL";

export const FOOD_FAILURE = "FOOD_FAILURE";

export const POST_FOOD_SUCCESSFULL = "POST_FOOD_SUCCESSFULL";
