export const COMMUNITY_REQUEST = "COMMUNITY_REQUEST";

export const COMMUNITY_SUCCESSFULL = "COMMUNITY_SUCCESSFULL";
export const ADD_TO_COMMUNITY_SUCCESSFUL = "ADD_TO_COMMUNITY_SUCCESSFUL";
export const GET_SINGLE_COMMUNITY_PRODUCT = "GET_SINGLE_COMMUNITY_PRODUCTT";

export const COMMUNITY_FAILURE = "COMMUNITY_FAILURE";


