export const COMMUNITY_REQUEST = "COMMUNITY_REQUEST";

export const COMMUNITY_SUCCESSFULL = "COMMUNITY_SUCCESSFULL";
export const ADD_TO_COMMUNITY_SUCCESSFUL = "ADD_TO_COMMUNITY_SUCCESSFUL"

export const COMMUNITY_FAILURE = "COMMUNITY_FAILURE";


